<?php
    $page = $_REQUEST['p'];
    $cate = $_REQUEST['cate'];
    // $page = 1;
    // $cate = 1;
    $arr = [
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'1'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'1'),


array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'2'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'2'),



array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'3'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'3'),


array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'4'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'4'),



array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'5'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'5'),


array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'999',"pic"=>'assets/images/categroy/7.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'43',"money"=>'189',"pic"=>'assets/images/categroy/8.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'6'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'6'),


array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'47',"money"=>'299',"pic"=>'assets/images/categroy/9.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'20',"money"=>'75',"pic"=>'assets/images/categroy/10.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'45',"money"=>'9.9',"pic"=>'assets/images/categroy/11.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'69',"money"=>'9.9',"pic"=>'assets/images/categroy/12.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'113',"pic"=>'assets/images/categroy/1.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'55',"money"=>'168',"pic"=>'assets/images/categroy/2.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'73',"money"=>'365',"pic"=>'assets/images/categroy/3.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'99',"money"=>'199',"pic"=>'assets/images/categroy/4.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'13',"money"=>'499',"pic"=>'assets/images/categroy/5.jpg','cate'=>'7'),
array("id"=>'1',"title"=>'长虹电热水壶CSH-18Y23深紫色 全网爆款 品质见证',"num"=>'46',"money"=>'399',"pic"=>'assets/images/categroy/6.jpg','cate'=>'7'),


    ];
    $newarr = [];
    foreach($arr as $val){
        if($val['cate'] == $cate){
            array_push($newarr,$val);
        }
    }
    // echo '<pre>';
    // print_r($newarr);
    // echo '</pre>';
 $offset = ($page-1)*12; //索引
  $length = 12;
  echo json_encode(array_slice($newarr,$offset,$length));

?>